import = [
  "~/.config/alacritty/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x=20, y=20 }
decorations = "None"

[font]
normal = { family = "Maple Mono", style="Regular" }
size = 11
